
package mesh.digitex.com;

import org.jdatepicker.impl.JDatePanelImpl;
import org.jdatepicker.impl.JDatePickerImpl;
import org.jdatepicker.impl.UtilDateModel;

/*
  @author @i-trace.mesh#
 */
public class Registration extends javax.swing.JFrame {
        
    public Registration() {
        initComponents();
    }
    int xMouse;
    int yMouse;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        FirstName = new javax.swing.JTextField();
        SecondName = new javax.swing.JTextField();
        LastName = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        BptFName = new javax.swing.JTextField();
        BptSName = new javax.swing.JTextField();
        BptLName = new javax.swing.JTextField();
        PhoneNumber = new javax.swing.JTextField();
        DateBPT = new javax.swing.JLabel();
        SerialNo = new javax.swing.JTextField();
        SaveBtn = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        Min = new javax.swing.JLabel();
        TopBar = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FirstName.setForeground(new java.awt.Color(0, 255, 0));
        FirstName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        FirstName.setText("First");
        FirstName.setBorder(null);
        FirstName.setOpaque(false);
        getContentPane().add(FirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 99, 203, 18));

        SecondName.setForeground(new java.awt.Color(0, 255, 0));
        SecondName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SecondName.setText("Second");
        SecondName.setBorder(null);
        SecondName.setOpaque(false);
        getContentPane().add(SecondName, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 99, 203, 18));

        LastName.setForeground(new java.awt.Color(0, 255, 0));
        LastName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        LastName.setText("Last");
        LastName.setBorder(null);
        LastName.setOpaque(false);
        getContentPane().add(LastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(718, 99, 180, 18));

        jComboBox1.setBackground(new java.awt.Color(152, 158, 163));
        jComboBox1.setForeground(new java.awt.Color(0, 255, 0));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Married", "Single" }));
        jComboBox1.setBorder(null);
        jComboBox1.setOpaque(false);
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 135, 203, 18));

        BptFName.setForeground(new java.awt.Color(0, 255, 0));
        BptFName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        BptFName.setText("First");
        BptFName.setBorder(null);
        BptFName.setOpaque(false);
        getContentPane().add(BptFName, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 209, 203, 18));

        BptSName.setForeground(new java.awt.Color(0, 255, 0));
        BptSName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        BptSName.setText("Second");
        BptSName.setToolTipText("");
        BptSName.setBorder(null);
        BptSName.setOpaque(false);
        getContentPane().add(BptSName, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 209, 203, 18));

        BptLName.setForeground(new java.awt.Color(0, 255, 0));
        BptLName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        BptLName.setText("Last");
        BptLName.setBorder(null);
        BptLName.setOpaque(false);
        getContentPane().add(BptLName, new org.netbeans.lib.awtextra.AbsoluteConstraints(716, 209, 180, 18));

        PhoneNumber.setForeground(new java.awt.Color(0, 255, 0));
        PhoneNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PhoneNumber.setText("254-");
        PhoneNumber.setBorder(null);
        PhoneNumber.setOpaque(false);
        getContentPane().add(PhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 360, 203, 18));

        DateBPT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DateBPTMouseClicked(evt);
            }
        });
        getContentPane().add(DateBPT, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 170, 205, 18));

        SerialNo.setForeground(new java.awt.Color(0, 255, 0));
        SerialNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SerialNo.setText("auto");
        SerialNo.setBorder(null);
        SerialNo.setOpaque(false);
        getContentPane().add(SerialNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 398, 203, 18));

        SaveBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaveBtnMouseClicked(evt);
            }
        });
        getContentPane().add(SaveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(774, 464, 100, 20));

        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 4, 28, 16));

        Min.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinMouseClicked(evt);
            }
        });
        getContentPane().add(Min, new org.netbeans.lib.awtextra.AbsoluteConstraints(804, 6, 24, 15));

        TopBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TopBarMousePressed(evt);
            }
        });
        TopBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                TopBarMouseDragged(evt);
            }
        });
        getContentPane().add(TopBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 12));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mesh/digitex/com/RegistrationChurch.png"))); // NOI18N
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void SaveBtnMouseClicked(java.awt.event.MouseEvent evt) {                                     
       {
        MainWin s= new MainWin();
           s.setVisible(true);
           this.dispose();
       }
    }                                    

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {                                   
       MainWin s= new MainWin();
           s.setVisible(true);
           this.dispose();
    }                                  

    private void MinMouseClicked(java.awt.event.MouseEvent evt) {                                 
        this.setState(Registration.ICONIFIED);
    }                                

    private void TopBarMouseDragged(java.awt.event.MouseEvent evt) {                                    
         int x = evt.getXOnScreen();
         int y = evt.getYOnScreen();
       
       this.setLocation(x- xMouse, y - yMouse); 
    }                                   

    private void TopBarMousePressed(java.awt.event.MouseEvent evt) {                                    
         int x = evt.getXOnScreen();
         int y = evt.getYOnScreen();
       
       this.setLocation(x- xMouse, y - yMouse); 
    }                                   

    private void DateBPTMouseClicked(java.awt.event.MouseEvent evt) {                                     
       UtilDateModel model = new UtilDateModel();
       
      
    }                                    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel BG;
    private javax.swing.JTextField BptFName;
    private javax.swing.JTextField BptLName;
    private javax.swing.JTextField BptSName;
    private javax.swing.JLabel DateBPT;
    private javax.swing.JTextField FirstName;
    private javax.swing.JTextField LastName;
    private javax.swing.JLabel Min;
    private javax.swing.JTextField PhoneNumber;
    private javax.swing.JLabel SaveBtn;
    private javax.swing.JTextField SecondName;
    private javax.swing.JTextField SerialNo;
    private javax.swing.JLabel TopBar;
    private javax.swing.JLabel close;
    private javax.swing.JComboBox jComboBox1;
    // End of variables declaration                   
}
